export type UseCase =
  | "出品準備"
  | "SEO対策"
  | "商品ページ改善"
  | "価格・利益設計"
  | "広告(RPP)運用"
  | "販促・クーポン設計"
  | "売上・KPI計画"
  | "在庫管理"
  | "レビュー対策"
  | "競合・市場調査";

export interface ToolMeta {
  slug: string;
  title: string;
  description: string;
  category: "画像" | "商品テキスト" | "HTML" | "CSV" | "リサーチ";
  status: "available" | "coming-soon";
  /** このツールをどんな業務タイミングで使うか（複数可） */
  useCases: UseCase[];
}

export const USE_CASE_ORDER: UseCase[] = [
  "出品準備",
  "SEO対策",
  "商品ページ改善",
  "競合・市場調査",
  "価格・利益設計",
  "販促・クーポン設計",
  "広告(RPP)運用",
  "売上・KPI計画",
  "在庫管理",
  "レビュー対策",
];

export const TOOLS: ToolMeta[] = [
  {
    slug: "image",
    title: "画像リサイズ・圧縮",
    description: "商品画像のリサイズ・圧縮・形式変換をブラウザだけで一括処理。",
    category: "画像",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "product-name",
    title: "商品名文字数チェッカー",
    description: "商品名の文字数・バイト数・使用文字・機種依存文字を瞬時にチェック。",
    category: "商品テキスト",
    status: "available",
    useCases: ["出品準備", "SEO対策"],
  },
  {
    slug: "zenkaku-hankaku",
    title: "全角／半角文字数チェック",
    description: "文字種別の件数を確認し、ワンクリックで全角⇔半角変換。",
    category: "商品テキスト",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "forbidden-chars",
    title: "禁止文字／機種依存文字チェック",
    description: "文字化け・登録エラーの原因になる文字を事前検出し、代替候補を提示。",
    category: "商品テキスト",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "html-format",
    title: "HTML整形",
    description: "読みにくいHTMLをインデント付きで自動整形。",
    category: "HTML",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "html-strip",
    title: "HTMLタグ除去",
    description: "HTMLからタグを取り除き、文字情報だけを抽出。",
    category: "HTML",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "csv-encoding",
    title: "CSV文字コード変換",
    description: "Shift_JIS・UTF-8などの文字コードを自動判定し、指定の形式へ変換。",
    category: "CSV",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "csv-extract",
    title: "CSV列抽出",
    description: "必要な列だけを選んで、並び順を指定した新しいCSVを生成。",
    category: "CSV",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "csv-dedupe",
    title: "CSV重複削除",
    description: "指定した列の値をもとに重複行を検出し、削除・抽出。",
    category: "CSV",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "csv-replace",
    title: "CSV一括置換",
    description: "指定した列の文字列をまとめて検索・置換。",
    category: "CSV",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "csv-excel",
    title: "CSV→Excel変換",
    description: "先頭行固定・オートフィルター付きのExcelファイルへ変換。",
    category: "CSV",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "csv-bulk-edit",
    title: "CSV商品一括編集",
    description: "対象列・条件を指定して商品CSVを一括置換・追加・削除。変更前後を必ず確認してから出力。",
    category: "CSV",
    status: "available",
    useCases: ["出品準備"],
  },
  {
    slug: "suggest",
    title: "サジェストキーワード収集",
    description: "起点キーワードから楽天市場の関連サジェストを階層的にまとめて収集。",
    category: "リサーチ",
    status: "available",
    useCases: ["SEO対策"],
  },
  {
    slug: "suggest-trend",
    title: "サジェスト差分・トレンド",
    description: "サジェスト取得結果を保存し、前回との差分（NEW/OUT/KEEP）を継続的に確認。",
    category: "リサーチ",
    status: "available",
    useCases: ["SEO対策"],
  },
  {
    slug: "product-seo-check",
    title: "商品名SEOチェッカー",
    description: "商品名と楽天サジェストを照合し、使用済み・未使用・NEWキーワードとカバー率を可視化。",
    category: "リサーチ",
    status: "available",
    useCases: ["SEO対策", "商品ページ改善"],
  },
  {
    slug: "rpp-analysis",
    title: "RPP広告分析",
    description: "RPPレポートCSVから商品別ROAS・CVR・CPCを自動算出し、対応すべき商品を優先表示。",
    category: "リサーチ",
    status: "available",
    useCases: ["広告(RPP)運用"],
  },
  {
    slug: "profit-simulator",
    title: "利益・値引きシミュレーター",
    description: "販売価格・原価・送料・ポイント・クーポン・広告費から1注文あたり利益と値引き余力を即計算。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計"],
  },
  {
    slug: "bulk-seo-check",
    title: "商品名一括SEO診断",
    description: "商品CSVとサジェストデータを照合し、商品名を見直すべき優先順位を一括で抽出。",
    category: "リサーチ",
    status: "available",
    useCases: ["SEO対策", "商品ページ改善"],
  },
  {
    slug: "promotion-comparator",
    title: "ポイント vs クーポン比較",
    description: "金額OFF・%OFF・ポイント還元を同条件で並べて比較し、利益への影響を一目で確認。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計", "販促・クーポン設計"],
  },
  {
    slug: "discount-volume",
    title: "値引き必要販売数シミュレーター",
    description: "現在価格・値下げ後価格・販売数・原価から、利益を維持するために必要な販売数増加率を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計"],
  },
  {
    slug: "price-increase",
    title: "値上げ許容販売減少率シミュレーター",
    description: "現在価格・値上げ後価格・販売数・原価から、利益を維持できる販売数の許容減少率を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計"],
  },
  {
    slug: "coupon-minimum-spend",
    title: "クーポン最低購入金額シミュレーター",
    description: "クーポン額・原価率・送料・販売関連費率・最低利益率から、採算が取れる最低購入金額を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計", "販促・クーポン設計"],
  },
  {
    slug: "max-point-rate",
    title: "最大ポイント倍率チェッカー",
    description: "販売価格・原価・送料・現在ポイント負担率から、利益率を維持できる最大ポイント負担率を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計"],
  },
  {
    slug: "bulk-purchase-coupon",
    title: "まとめ買いクーポン採算チェッカー",
    description: "商品単価・原価・購入点数・クーポン額から、まとめ買い施策で本当に利益が増えるかを3シナリオで比較。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計", "販促・クーポン設計"],
  },
  {
    slug: "free-shipping-volume",
    title: "送料無料化必要販売増加率シミュレーター",
    description: "商品価格・原価・実配送コスト・現在顧客送料から、送料無料化後に利益を維持できる必要販売増加率を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["価格・利益設計"],
  },
  {
    slug: "rpp-required-cvr",
    title: "RPP必要CVRシミュレーター",
    description: "販売価格・CPC・原価・送料・最低利益率から、そのCPCを成立させるために必要な商品ページCVRを即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["広告(RPP)運用", "商品ページ改善"],
  },
  {
    slug: "cpc-limit-matrix",
    title: "CVR別CPC上限マトリクス",
    description: "販売価格・原価・送料・最低利益率から、CVRごとに許容できる最大CPCを一覧表示。",
    category: "リサーチ",
    status: "available",
    useCases: ["広告(RPP)運用"],
  },
  {
    slug: "rpp-click-runway",
    title: "RPP赤字まであと何クリックシミュレーター",
    description: "現在の広告費・クリック数・注文数から、利益維持ライン／損益分岐ラインまでの残りクリック数を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["広告(RPP)運用"],
  },
  {
    slug: "ad-budget-scaling",
    title: "広告予算増額シミュレーター",
    description: "現在の広告費・売上・原価率・最低利益率から、増額後の広告予算を成立させる必要売上・必要ROASを逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["広告(RPP)運用", "売上・KPI計画"],
  },
  {
    slug: "sales-target-reverse",
    title: "売上目標逆算シミュレーター",
    description: "売上目標・平均注文単価・想定CVRから、必要注文数・必要アクセス数・日割り目標を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画"],
  },
  {
    slug: "sale-target",
    title: "SALE目標売上・必要販売数シミュレーター",
    description: "通常価格・SALE価格・目標売上・SALE期間から、目標達成に必要な販売数と日販を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画", "販促・クーポン設計"],
  },
  {
    slug: "coupon-budget",
    title: "クーポン予算・必要売上シミュレーター",
    description: "クーポン額・想定利用数・平均注文単価・原価率から、施策全体の原資・必要売上・利益を算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["販促・クーポン設計"],
  },
  {
    slug: "inventory-clearance",
    title: "在庫消化に必要な販売数・価格シミュレーター",
    description: "現在在庫数・消化目標日数・現在販売ペースから、期限内消化に必要な日販と現在ペースとの差を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["在庫管理"],
  },
  {
    slug: "inventory-markdown-limit",
    title: "在庫消化値下げ上限・利益許容額シミュレーター",
    description: "在庫数・現在価格・許容できる利益減少額から、利益条件を満たせる最低販売価格と最大値下げ率を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["在庫管理", "価格・利益設計"],
  },
  {
    slug: "bulk-purchase-rate",
    title: "客単価目標・必要まとめ買い率シミュレーター",
    description: "1個購入とまとめ買い時の注文金額・目標客単価から、目標達成に必要なまとめ買い注文の比率を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画", "販促・クーポン設計"],
  },
  {
    slug: "free-shipping-threshold-aov",
    title: "送料無料ライン目標・必要客単価シミュレーター",
    description: "現在客単価と送料無料ラインから、ライン到達に必要な客単価の差額・上昇率を即算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画", "販促・クーポン設計"],
  },
  {
    slug: "new-customer-target",
    title: "売上目標達成・必要新規顧客数シミュレーター",
    description: "売上目標・新規以外の売上・新規顧客AOVから、目標達成に必要な新規顧客数を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画"],
  },
  {
    slug: "review-rating-target",
    title: "レビュー評価目標・必要★5件数シミュレーター",
    description: "現在レビュー件数・平均評価・目標評価から、目標達成に必要な★5レビュー件数を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["レビュー対策"],
  },
  {
    slug: "low-rating-impact",
    title: "低評価レビュー1件の影響・回復必要件数シミュレーター",
    description: "現在レビュー件数・平均評価に低評価が追加された場合の新平均と、元評価への回復に必要な★5件数を算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["レビュー対策"],
  },
  {
    slug: "repeat-rate-target",
    title: "リピート率目標・必要リピーター数シミュレーター",
    description: "総顧客数・現在リピーター数・目標リピート率から、目標達成に必要なリピーター人数を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画"],
  },
  {
    slug: "repeat-sales-target",
    title: "リピート売上目標・必要再購入件数シミュレーター",
    description: "リピート売上目標・現在リピート売上・平均再購入単価から、目標達成に必要な再購入件数を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画"],
  },
  {
    slug: "profit-target",
    title: "月間利益目標・必要売上／販売数シミュレーター",
    description: "利益目標・利益率または1個利益から、目標達成に必要な売上額または販売数を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画", "価格・利益設計"],
  },
  {
    slug: "fixed-cost-break-even",
    title: "固定費回収・必要販売数シミュレーター",
    description: "固定費と1個あたり限界利益から、固定費回収に必要な最低販売数（損益分岐販売数）を逆算。",
    category: "リサーチ",
    status: "available",
    useCases: ["売上・KPI計画"],
  },
  {
    slug: "competitor-analysis",
    title: "楽天市場 競合商品分析ツール",
    description: "検索キーワードから競合商品の公開情報を一括取得し、価格・レビュー・送料・ポイント・ショップ集中度を数値化。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査"],
  },
  {
    slug: "price-position-analysis",
    title: "楽天市場 価格ポジショニング分析ツール",
    description: "競合商品価格を取得し、市場価格中央値・価格帯構成・レビュー帯別価格から自社価格の市場内ポジションを診断。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査", "価格・利益設計"],
  },
  {
    slug: "review-barrier-analysis",
    title: "楽天市場 レビュー参入障壁分析ツール",
    description: "競合商品のレビュー件数・評価を取得し、市場全体・API標準順上位30商品のレビュー資産からレビュー参入障壁を100点満点で診断。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査", "レビュー対策"],
  },
  {
    slug: "promotion-competition-analysis",
    title: "楽天市場 ポイント・送料無料競争分析ツール",
    description: "競合商品の送料条件・商品別ポイント倍率を取得し、市場でどの程度送料無料・ポイントアップが一般化しているかを診断。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査", "販促・クーポン設計"],
  },
  {
    slug: "keyword-competition-checker",
    title: "楽天SEOキーワード競合度チェッカー",
    description: "複数キーワード候補の検索商品数・レビュー・価格・ショップ集中度を比較し、競合度と競合余地スコアを一括算出。",
    category: "リサーチ",
    status: "available",
    useCases: ["SEO対策", "競合・市場調査"],
  },
  {
    slug: "shop-composition-analysis",
    title: "楽天市場 競合ショップ商品構成分析ツール",
    description: "競合ショップのshopCodeから掲載商品群を取得し、価格帯・ジャンル構成・レビュー資産・主力候補商品を分析。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査"],
  },
  {
    slug: "title-seo-analysis",
    title: "楽天SEO競合タイトル分析ツール",
    description: "競合商品の商品名・キャッチコピーを分析し、商品使用率の高いキーワードとカテゴリ構成、自社タイトルの不足キーワードを抽出。",
    category: "リサーチ",
    status: "available",
    useCases: ["SEO対策", "商品ページ改善", "競合・市場調査"],
  },
  {
    slug: "attribute-competition-analysis",
    title: "楽天市場 商品属性×競争力分析ツール",
    description: "指定ジャンルの商品属性ごとに商品数・価格・レビュー・ショップ数を比較し、同一ジャンル内の競争環境の違いを発見。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査"],
  },
  {
    slug: "market-gap-finder",
    title: "楽天市場 空白市場発見ツール",
    description: "ジャンル内商品を属性×価格帯×属性の組み合わせへ分解し、競争条件が比較的手薄な市場セルを競争余地スコアで抽出。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査"],
  },
  {
    slug: "shop-diff-checker",
    title: "楽天市場 13店舗 商品設定差異チェックツール",
    description: "複数店舗で販売する同一商品の価格・販売可否・送料・商品名・ジャンル・ポイント倍率の設定差異を一括検出。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査", "出品準備"],
  },
  {
    slug: "price-watch",
    title: "楽天市場 タイムセール・価格監視ツール",
    description: "登録商品の現在価格・SALE設定・ポイント倍率・送料・販売可否を取得し、前回チェック時からの変化をオンデマンドで検出。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査", "価格・利益設計"],
  },
  {
    slug: "change-detection",
    title: "楽天市場 新商品・競合商品変化検知ツール",
    description: "競合ショップの商品集合を取得し、前回チェック時からの新規検出商品・確認不可商品・価格や商品名等の変更をオンデマンドで検出。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査"],
  },
  {
    slug: "price-research",
    title: "楽天市場 価格調査ツール",
    description: "競合価格を取得し市場価格分布・自社価格ポジションを分析。価格履歴はサーバーに保存せず、この端末のブラウザ内（IndexedDB）にのみ保存。",
    category: "リサーチ",
    status: "available",
    useCases: ["競合・市場調査", "価格・利益設計"],
  },
];

export const CATEGORY_ORDER: ToolMeta["category"][] = [
  "画像",
  "商品テキスト",
  "HTML",
  "CSV",
  "リサーチ",
];
